---
abstract: 'The great new Acme::MyFirstModule::WWILLIS!'
author:
  - 'Will Willis <wwillis@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-MyFirstModule-WWILLIS
provides:
  Acme::MyFirstModule::WWILLIS:
    file: lib/Acme/MyFirstModule/WWILLIS.pm
    version: 0.02
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
